# Interactive palette chooser over the sampled palette posterior (PoC)
#
# Requires the posterior generated by scripts/poc-palette-sampling.R:
#   scripts/palette-posterior/palette-posterior.rds
#
# Launch with:
#   Rscript -e 'source("scripts/palette-chooser-app.R"); app <- build_palette_chooser(); shiny::runApp(app)'
#
# The sampler never re-runs: moving the weight sliders only re-scores and
# re-ranks precomputed per-draw metrics ("derived quantities"), so the
# interaction is instant.

library(shiny)

WEIGHT_METRICS <- c("cvd_safe", "min_dist", "mean_chroma", "lightness_spread")
METRIC_LABELS <- c(
  cvd_safe = "CVD-safe min distance",
  min_dist = "Normal-vision min distance",
  mean_chroma = "Mean chroma (colorfulness)",
  lightness_spread = "Lightness spread"
)

palette_hex <- function(pal) {
  rgb <- farver::convert_colour(pal, "oklab", "rgb") / 255
  grDevices::rgb(rgb[, 1], rgb[, 2], rgb[, 3])
}

swatch_ggplot <- function(pal, title = NULL, text_size = 3.5) {
  hex <- palette_hex(pal)
  df <- data.frame(
    x = factor(seq_len(nrow(pal)), levels = seq_len(nrow(pal))),
    hex = hex,
    lab = toupper(hex),
    text_col = ifelse(pal[, 1] > 0.5, "black", "white")
  )
  ggplot2::ggplot(df, ggplot2::aes(x, 1, fill = hex)) +
    ggplot2::geom_tile(color = "white", linewidth = 2) +
    ggplot2::geom_text(
      ggplot2::aes(label = lab),
      angle = 90, size = text_size,
      color = df$text_col,
      vjust = 0.35
    ) +
    ggplot2::scale_fill_identity() +
    ggplot2::labs(title = title) +
    ggplot2::theme_void(base_size = 11) +
    ggplot2::theme(plot.title = ggplot2::element_text(size = 10))
}

rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  if (diff(rng) < 1e-12) return(rep(0.5, length(x)))
  (x - rng[1]) / rng[1]
}

#' Build the chooser shiny app
#' @param rds_path Path to palette-posterior.rds (fit + metrics).
#' @return A shiny app object.
build_palette_chooser <- function(
  rds_path = "scripts/palette-posterior/palette-posterior.rds"
) {
  post <- readRDS(rds_path)
  met <- post$met
  met$.row <- seq_len(nrow(met))

  ui <- fluidPage(
    titlePanel("huerd palette chooser -- posterior draws, weighted metrics"),
    sidebarLayout(
      sidebarPanel(
        width = 3,
        p(
          "Each point is one palette sampled from the quality posterior.",
          "Weights re-rank the draws instantly; click a point to inspect",
          "that palette."
        ),
        lapply(WEIGHT_METRICS, function(m) {
          sliderInput(
            inputId = paste0("w_", m),
            label = METRIC_LABELS[[m]],
            min = 0, max = 3, value = 1, step = 0.1
          )
        }),
        numericInput("top_n", "Number of top palettes", value = 8, min = 1, max = 24),
        hr(),
        verbatimTextOutput("hint")
      ),
      mainPanel(
        plotOutput("metric_space", height = "320px",
          click = clickOpts("plot_click")),
        plotOutput("selected_palette", height = "140px"),
        uiOutput("top_palettes")
      )
    )
  )

  server <- function(input, output, session) {
    ranked <- reactive({
      w <- vapply(
        WEIGHT_METRICS,
        function(m) input[[paste0("w_", m)]],
        numeric(1)
      )
      score <- Reduce(`+`, lapply(names(w), function(m) w[[m]] * rescale01(met[[m]])))
      met$.score <- score
      met[order(-met$.score), ]
    })

    output$hint <- renderText({
      r <- ranked()
      sprintf(
        "draws: %d\nscore range: [%.2f, %.2f]\ntop draw: cvd %.3f, dist %.3f",
        nrow(r), min(r$.score), max(r$.score),
        r$cvd_safe[1], r$min_dist[1]
      )
    })

    output$metric_space <- renderPlot({
      r <- ranked()
      sel <- selected_row()
      ggplot2::ggplot(r, ggplot2::aes(min_dist, cvd_safe)) +
        ggplot2::geom_point(
          ggplot2::aes(color = .score),
          size = ifelse(r$.score == max(r$.score), 3, 1.2),
          alpha = 0.6
        ) +
        ggplot2::scale_color_viridis_c(option = "magma", name = "weighted score") +
        (if (!is.null(sel)) {
          ggplot2::geom_point(
            data = r[sel, , drop = FALSE],
            shape = 21, color = "black", fill = NA, size = 5, stroke = 1.2
          )
        }) +
        ggplot2::labs(
          x = "min perceptual distance (normal vision)",
          y = "min CVD-safe distance",
          title = "Palette posterior in metric space"
        ) +
        ggplot2::theme_minimal(base_size = 11)
    })

    selected_row <- reactive({
      click <- input$plot_click
      if (is.null(click)) return(NULL)
      r <- ranked()
      d <- sqrt(
        (r$min_dist - click$x)^2 / diff(range(r$min_dist))^2 +
          (r$cvd_safe - click$y)^2 / diff(range(r$cvd_safe))^2
      )
      which.min(d)
    })

    output$selected_palette <- renderPlot({
      r <- ranked()
      i <- selected_row()
      if (is.null(i)) {
        return(swatch_ggplot(r$palette[[1]], "Top palette under current weights"))
      }
      row <- r[i, ]
      swatch_ggplot(
        row$palette[[1]],
        sprintf("Selected draw (chain %d, draw %d): cvd %.3f | dist %.3f | chroma %.3f",
          row$.chain, row$.draw, row$cvd_safe, row$min_dist, row$mean_chroma)
      )
    })

    output$top_palettes <- renderUI({
      n <- min(input$top_n, nrow(ranked()))
      plot_output_list <- lapply(seq_len(n), function(i) {
        plotOutput(paste0("top_", i), height = "90px")
      })
      do.call(tagList, plot_output_list)
    })
    local({
      n_max <- 24
      for (i in seq_len(n_max)) {
        local({
          ii <- i
          output[[paste0("top_", ii)]] <- renderPlot({
            r <- ranked()
            if (ii > min(input$top_n, nrow(r))) return(NULL)
            swatch_ggplot(
              r$palette[[ii]],
              sprintf("%d. cvd %.3f | dist %.3f | chroma %.3f | Lspread %.2f",
                ii, r$cvd_safe[ii], r$min_dist[ii], r$mean_chroma[ii],
                r$lightness_spread[ii]),
              text_size = 3
            )
          })
        })
      }
    })
  }

  shinyApp(ui = ui, server = server)
}
app <- build_palette_chooser()
