#' Print Method for huerd_palette Objects
#'
#' Custom print method for color palettes generated by `huerd`.
#' Displays the colors and a brief summary of quality metrics if available.
#'
#' @param x An object of class `huerd_palette` (a character vector of hex colors).
#' @param ... Additional arguments (not used).
#' @export
#' @method print huerd_palette
print.huerd_palette <- function(x, ...) {
  n <- length(x)
  cat(
    "\n-- huerd Color Palette (",
    n,
    " color",
    if (n != 1) "s",
    ") --\n",
    sep = ""
  )

  if (n > 0) {
    max_display <- 20
    colors_to_display <- if (n > max_display) utils::head(x, max_display) else x

    cat("Colors:\n")
    print_color_vector(colors_to_display, indent = "")

    if (n > max_display) {
      cat(
        "  ... and ",
        n - max_display,
        " more color",
        if ((n - max_display) != 1) "s",
        ".\n",
        sep = ""
      )
    }
  } else {
    cat("  (empty palette)\n")
  }

  metrics <- attr(x, "metrics")
  if (!is.null(metrics) && inherits(metrics, "huerd_evaluation")) {
    cat("\n-- Quality Metrics Summary --\n")
    cat(
      "* Min. Perceptual Distance (OKLAB): ",
      sprintf('%.3f', metrics$distances$min %||% NA_real_),
      "\n",
      sep = ""
    )
    cat(
      "* Optimizer Performance Ratio      : ",
      sprintf('%.1f%%', (metrics$distances$performance_ratio %||% 0) * 100),
      "\n",
      sep = ""
    )
    cat(
      "* Min. CVD-Safe Distance (OKLAB)  : ",
      sprintf('%.3f', metrics$cvd_safety$worst_case_min_distance %||% NA_real_),
      "\n",
      sep = ""
    )
  }

  opt_details <- attr(x, "optimization_details")
  if (!is.null(opt_details)) {
    cat("\n-- Generation Details --\n")
    cat(
      "* Optimizer Iterations: ",
      opt_details$iterations %||% 'N/A',
      "\n",
      sep = ""
    )
    cat(
      "* Optimizer Status: ",
      opt_details$status_message %||% 'N/A',
      "\n",
      sep = ""
    )
  }
  invisible(x)
}


#' Print Method for huerd_evaluation Objects
#'
#' Custom print method for evaluation results from `evaluate_palette`.
#'
#' @param x An object of class `huerd_evaluation`.
#' @param ... Additional arguments (not used).
#' @export
#' @method print huerd_evaluation
print.huerd_evaluation <- function(x, ...) {
  cat(
    "\n-- huerd Palette Evaluation (",
    x$n_colors,
    " color",
    if (x$n_colors != 1) "s",
    ") --\n",
    sep = ""
  )

  if (x$n_colors < 2) {
    cat("Metrics are limited for palettes with fewer than 2 colors.\n")
    return(invisible(x))
  }

  cat("\n-- Perceptual Distances (OKLAB) --\n")
  cat(
    "* Min distance       : ",
    sprintf('%.4f', x$distances$min),
    "\n",
    sep = ""
  )
  cat(
    "* Mean distance      : ",
    sprintf('%.4f', x$distances$mean),
    "\n",
    sep = ""
  )
  cat(
    "* Median distance    : ",
    sprintf('%.4f', x$distances$median),
    "\n",
    sep = ""
  )
  cat(
    "* Std. Dev.          : ",
    sprintf('%.4f', x$distances$sd),
    "\n",
    sep = ""
  )
  cat(
    "* Estimated Max Min  : ",
    sprintf('%.4f', x$distances$estimated_max),
    " (for unconstrained palette of this size)\n",
    sep = ""
  )
  cat(
    "* Performance Ratio  : ",
    sprintf('%.1f%%', x$distances$performance_ratio * 100),
    " (achieved min / estimated max)\n",
    sep = ""
  )

  cat("\n-- CVD Safety (OKLAB distances under simulation) --\n")
  cat(
    "* Worst-case min dist: ",
    sprintf('%.4f', x$cvd_safety$worst_case_min_distance),
    "\n",
    sep = ""
  )
  cat(
    "  Protanopia : min=",
    sprintf('%.3f', x$cvd_safety$protan$min_distance),
    ", preserved_ratio=",
    sprintf('%.2f', x$cvd_safety$protan$preserved_ratio),
    "\n",
    sep = ""
  )
  cat(
    "  Deuteranopia: min=",
    sprintf('%.3f', x$cvd_safety$deutan$min_distance),
    ", preserved_ratio=",
    sprintf('%.2f', x$cvd_safety$deutan$preserved_ratio),
    "\n",
    sep = ""
  )
  cat(
    "  Tritanopia : min=",
    sprintf('%.3f', x$cvd_safety$tritan$min_distance),
    ", preserved_ratio=",
    sprintf('%.2f', x$cvd_safety$tritan$preserved_ratio),
    "\n",
    sep = ""
  )

  cat("\n-- Color Distribution (OKLAB) --\n")
  cat(
    "* Lightness (L)    : range=[",
    sprintf('%.2f', x$distribution$lightness_oklab$range[1]),
    ", ",
    sprintf('%.2f', x$distribution$lightness_oklab$range[2]),
    "], mean=",
    sprintf('%.2f', x$distribution$lightness_oklab$mean),
    "\n",
    sep = ""
  )
  cat(
    "* Chroma (C)       : range=[",
    sprintf('%.3f', x$distribution$chroma_oklab$range[1]),
    ", ",
    sprintf('%.3f', x$distribution$chroma_oklab$range[2]),
    "], mean=",
    sprintf('%.3f', x$distribution$chroma_oklab$mean),
    "\n",
    sep = ""
  )
  cat(
    "* Hue (degrees)    : circular_variance=",
    sprintf('%.3f', x$distribution$hue_oklab$circular_variance),
    "\n",
    sep = ""
  )

  # No subjective heuristic score in pure data provider mode
  invisible(x)
}


#' Print Method for huerd_simulation_result Objects
#'
#' Custom print method for simulation results from `simulate_palette_cvd`.
#'
#' @param x An object of class `huerd_simulation_result`.
#' @param ... Additional arguments (not used).
#' @export
#' @method print huerd_simulation_result
print.huerd_simulation_result <- function(x, ...) {
  sim_type_attr <- attr(x, "cvd_type") %||% "unknown"
  severity_attr <- attr(x, "severity") %||% NA_real_

  if (is.list(x) && "original" %in% names(x)) {
    cat(
      "\n-- huerd CVD Simulation Result (Multiple Types, Severity: ",
      sprintf('%.2f', severity_attr),
      ") --\n",
      sep = ""
    )
    for (type in names(x)) {
      cat("Palette for: ", type, "\n", sep = "")
      colors_vec <- x[[type]]
      if (length(colors_vec) == 0) {
        cat("  (empty palette)\n")
      } else {
        print_color_vector(colors_vec)
      }
    }
  } else if (is.character(x)) {
    cat(
      "\n-- huerd CVD Simulation Result (Type: ",
      sim_type_attr,
      ", Severity: ",
      sprintf('%.2f', severity_attr),
      ") --\n",
      sep = ""
    )
    print_color_vector(x)
  } else {
    cat("\n-- huerd CVD Simulation Result --\n")
    cat("Unrecognized simulation result format.\n")
    utils::str(x)
  }
  invisible(x)
}


#' Check if color is valid hex format
#' @noRd
.is_valid_hex_color <- function(color_val) {
  !is.na(color_val) &&
    grepl("^#[0-9A-Fa-f]{6}$", color_val, ignore.case = TRUE)
}

#' Calculate sRGB luminance for color contrast
#' @noRd
.calculate_luminance <- function(color_val) {
  col_rgb <- grDevices::col2rgb(color_val)
  srgb_red_weight <- 0.2126
  srgb_green_weight <- 0.7152
  srgb_blue_weight <- 0.0722
  (srgb_red_weight *
    col_rgb[1, 1] +
    srgb_green_weight * col_rgb[2, 1] +
    srgb_blue_weight * col_rgb[3, 1]) /
    255.0
}

#' Print a single color with swatch
#' @noRd
.print_color_with_swatch <- function(color_val, item_label) {
  if (!.is_valid_hex_color(color_val)) {
    cat(item_label, " (invalid/NA color)\n", sep = "")
    return()
  }

  cat(item_label, "\n", sep = "")
}

#' Print a single color item (with or without swatch)
#' @noRd
.print_color_item <- function(color_val, item_label) {
  .print_color_with_swatch(color_val, item_label)
}

#' Internal helper to print a vector of colors with swatches
#' @noRd
print_color_vector <- function(colors_vec, indent = "  ") {
  if (length(colors_vec) == 0) {
    cat("  (empty palette)\n")
    return(invisible(NULL))
  }

  for (i in seq_along(colors_vec)) {
    color_val <- colors_vec[i]
    item_label <- sprintf("%s[%2d] %s", indent, i, color_val)
    .print_color_item(color_val, item_label)
  }
}
